Fill column and row with 0 wherever you find one

# Approach 1
Maintain an extra array of same length to track the rows and columns where there is 0. Iterate and fill the row and columns with 0


In [37]:
def fillRowColumnWithZeroV1(arr):

    store = np.array([[-1] * len(arr[0]) for i in range(len(arr))])
    for i in range(len(arr)):
        for j in range(len(arr[0])):

            if arr[i, j] == 0:
                store[i, j] = 0
    print(store)
    for i in range(len(store)):
        for j in range(len(store[0])):

            if store[i, j] == 0:
                arr[i, :] = 0
                arr[:, j] = 0

    return arr


import numpy as np
arr = np.array([[-1] * 3 for i in range(3)])
arr[0, 0] = arr[2, 2] = 0
print(arr)
# print(fillRowColumnWithZero(arr))

[[ 0 -1 -1]
 [-1 -1 -1]
 [-1 -1  0]]


# Approach 2

We can only store one array for row and one for columns. <br>
Because it is sufficient for us to know that the row and column make the whole row and column zero.


In [38]:
def fillRowsAndColumnsV2(arr):

    rows = np.ones((arr.shape[0],),dtype= int)
    cols = np.ones((arr.shape[1],),dtype= int)
    
    for i in range(arr.shape[0]):
        for j in range(arr.shape[1]):
            
            if arr[i,j] == 0:
                rows[i] = cols[j] = 0
                
    
    for i in range(arr.shape[0]):
        if rows[i]==0 :
            arr[i,:] = 0 
        
    for j in range(arr.shape[1]):
        if cols[j]==0: 
            arr[:,j]=0
    print(arr)
fillRowsAndColumnsV2(arr)

[[ 0  0  0]
 [ 0 -1  0]
 [ 0  0  0]]
