# Problem: Sort an array using selection sort

1. Find the minimum element
2. Place it into the first position.
3. Similarly find the second minimum element and place it on position second.

Time Complexity : O(n^2) <br>
Space Complexity : O(1)

In [1]:
import sys 

def selectionSort(A):
    
    for i in range(len(A)):
        
        
    # find the minimum element:
        min_value = sys.maxsize
        min_index = i
        for j in range(i,len(A)):
            
            min_value = min(min_value,A[j])
            min_index = A.index(min_value)
         
        A[i],A[min_index] = A[min_index], A[i]
        print(A)
        
    return A
        
selectionSort([5,4,3,2,1])

[1, 4, 3, 2, 5]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


[1, 2, 3, 4, 5]

# Without using for loop

In [2]:
import sys


def selectionSort(A):

    for i in range(len(A)):

        # find the minimum element:
        min_value = sys.maxsize
        min_index = i

        min_value = min(A[i:])
        min_index = A.index(min_value)

        A[i], A[min_index] = A[min_index], A[i]
        print(A)

    return A


selectionSort([5, 4, 3, 2, 1])

[1, 4, 3, 2, 5]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


[1, 2, 3, 4, 5]

# Solved using numpy

In [3]:
import sys
import numpy as np


def selectionSort(A):

    for i in range(len(A)):

        # find the minimum element:
        min_value = sys.maxsize
        min_index = i

        min_value = np.min(A[i:])
        min_index = np.where(A == min_value)

        A[i], A[min_index] = A[min_index], A[i]
        print(A)

    return A


selectionSort(np.array([5, 4, 3, 2, 1]))

[1 4 3 2 5]
[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]


array([1, 2, 3, 4, 5])